// 可拖动图标悬浮窗 - 单例实现
// 使用方式: Java.perform(() => { const floatIcon = new FloatIcon('{base64_icon}'); })

const FloatIcon = (function () {
  let instance = null;

  function FloatIcon(iconBase64, options = {}) {
    if (instance) {
      console.log("[FloatIcon] 实例已存在，返回现有实例");
      return instance;
    }

    this.iconBase64 = iconBase64;
    this.options = {
      iconSize: options.iconSize || 60,
      menuWidth: options.menuWidth || 300,
      menuHeight: options.menuHeight || 200,
      iconX: options.iconX || 100,
      iconY: options.iconY || 100,
      menuX: options.menuX || 200,
      menuY: options.menuY || 200,
      ...options,
    };

    this.context = null;
    this.windowManager = null;
    this.iconView = null;
    this.menuLayout = null;
    this.iconParams = null;
    this.menuParams = null;
    this.isMenuShown = false;
    this.isIconShown = false;

    // 拖动相关
    this.lastX = 0;
    this.lastY = 0;
    this.isDragging = false;
    this.dragStartTime = 0;

    instance = this;
    this.init();
  }

  FloatIcon.prototype.init = function () {
    try {
      Java.scheduleOnMainThread(() => {
        this.createViews();
      });
    } catch (error) {
      console.error("[FloatIcon] 初始化失败:", error);
    }
  };
  function findActivity(name) {
    return new Promise((resolve) => {
      let result = null;
      Java.choose(name, {
        onMatch(instance) {
          result = instance;
          return "stop";
        },
        onComplete() {
          resolve(result);
        },
      });
    });
  }
  FloatIcon.prototype.createViews = async function () {
    try {
      // 获取 Context 和 WindowManager
      const Context = Java.use("android.content.Context");
      const foundActivity = await findActivity(
        "com.r2games.myhero.aligames.MainActivity",
      );
      // this.context = foundActivity;

      this.context = Java.use("android.app.ActivityThread")
        .currentApplication()
        .getApplicationContext();

      this.windowManager = Java.cast(
        foundActivity.getSystemService(Context.WINDOW_SERVICE.value),
        Java.use("android.view.ViewManager"),
      );
      //   this.windowManager = foundActivity.getWindowManager();

      // 创建图标视图
      this.createIconView();

      // 创建菜单视图
      this.createMenuView();

      console.log("[FloatIcon] 初始化完成");
    } catch (error) {
      console.error("[FloatIcon] 创建视图失败:", error);
    }
  };

  FloatIcon.prototype.createIconView = function () {
    try {
      const ImageView = Java.use("android.widget.ImageView");
      const BitmapFactory = Java.use("android.graphics.BitmapFactory");
      const Base64 = Java.use("android.util.Base64");
      const LayoutParams = Java.use("android.view.WindowManager$LayoutParams");

      // 解码 base64 图标
      const decoded = Base64.decode(this.iconBase64, Base64.DEFAULT.value);
      const bitmap = BitmapFactory.decodeByteArray(decoded, 0, decoded.length);

      // 创建 ImageView
      this.iconView = ImageView.$new(this.context);
      this.iconView.setImageBitmap(bitmap);

      // 设置布局参数
      this.iconParams = LayoutParams.$new();
      this.iconParams.type = LayoutParams.TYPE_APPLICATION_OVERLAY.value;
      this.iconParams.flags =
        LayoutParams.FLAG_NOT_FOCUSABLE.value |
        LayoutParams.FLAG_NOT_TOUCH_MODAL.value;
      this.iconParams.format = Java.use(
        "android.graphics.PixelFormat",
      ).TRANSLUCENT.value;
      this.iconParams.width = this.options.iconSize;
      this.iconParams.height = this.options.iconSize;
      this.iconParams.x = this.options.iconX;
      this.iconParams.y = this.options.iconY;

      // 设置触摸事件（拖动和点击）
      this.setupIconTouchListener();
    } catch (error) {
      console.error("[FloatIcon] 创建图标视图失败:", error);
    }
  };

  FloatIcon.prototype.setupIconTouchListener = function () {
    try {
      const MotionEvent = Java.use("android.view.MotionEvent");
      const OnTouchListener = Java.use("android.view.View$OnTouchListener");
      const self = this;

      const touchListener = Java.registerClass({
        name: "com.frida.FloatIconTouchListener" + Date.now(),
        implements: [OnTouchListener],
        methods: {
          onTouch: function (view, event) {
            const action = event.getAction();

            switch (action) {
              case MotionEvent.ACTION_DOWN.value:
                self.lastX = event.getRawX();
                self.lastY = event.getRawY();
                self.isDragging = false;
                self.dragStartTime = Date.now();
                return true;

              case MotionEvent.ACTION_MOVE.value:
                const deltaX = event.getRawX() - self.lastX;
                const deltaY = event.getRawY() - self.lastY;

                if (Math.abs(deltaX) > 10 || Math.abs(deltaY) > 10) {
                  self.isDragging = true;
                  self.iconParams.x += deltaX;
                  self.iconParams.y += deltaY;
                  self.windowManager.updateViewLayout(
                    self.iconView,
                    self.iconParams,
                  );
                  self.lastX = event.getRawX();
                  self.lastY = event.getRawY();
                }
                return true;

              case MotionEvent.ACTION_UP.value:
              case MotionEvent.ACTION_CANCEL.value:
                const dragDuration = Date.now() - self.dragStartTime;
                if (!self.isDragging && dragDuration < 300) {
                  self.toggleMenu();
                }
                return true;
            }
            return false;
          },
        },
      });

      this.iconView.setOnTouchListener(touchListener.$new());
    } catch (error) {
      console.error("[FloatIcon] 设置触摸监听失败:", error);
    }
  };

  FloatIcon.prototype.createMenuView = function () {
    try {
      const LinearLayout = Java.use("android.widget.LinearLayout");
      const TextView = Java.use("android.widget.TextView");
      const Button = Java.use("android.widget.Button");
      const LayoutParams = Java.use("android.view.WindowManager$LayoutParams");
      const Color = Java.use("android.graphics.Color");
      const JString = Java.use("java.lang.String");

      // 创建菜单容器
      this.menuLayout = LinearLayout.$new(this.context);
      this.menuLayout.setOrientation(LinearLayout.VERTICAL.value);
      // this.menuLayout.setBackgroundColor(Color.parseColor("#CC000000"));
      this.menuLayout.setBackgroundColor(Color.parseColor("#00000000")); // 完全透明
      // 标题
      const titleText = TextView.$new(this.context);
      titleText.setText(JString.$new("悬浮菜单"));
      titleText.setTextSize(18);
      titleText.setTextColor(Color.WHITE.value);
      titleText.setPadding(20, 20, 20, 20);
      this.menuLayout.addView(titleText);

      // 最小化按钮
      const minimizeBtn = Button.$new(this.context);
      minimizeBtn.setText(JString.$new("最小化"));
      minimizeBtn.setTextSize(16);
      minimizeBtn.setTextColor(Color.WHITE.value);
      minimizeBtn.setBackgroundColor(Color.parseColor("#FF4444"));

      const btnParams = Java.use(
        "android.widget.LinearLayout$LayoutParams",
      ).$new(
        Java.use("android.view.ViewGroup$LayoutParams").MATCH_PARENT.value,
        Java.use("android.view.ViewGroup$LayoutParams").WRAP_CONTENT.value,
      );
      btnParams.setMargins(20, 10, 20, 20);
      minimizeBtn.setLayoutParams(btnParams);

      const self = this;
      const OnClickListener = Java.use("android.view.View$OnClickListener");
      const clickListener = Java.registerClass({
        name: "com.frida.FloatMinimizeClickListener" + Date.now(),
        implements: [OnClickListener],
        methods: {
          onClick: function (view) {
            self.hideMenu();
            self.showIcon();
          },
        },
      });

      minimizeBtn.setOnClickListener(clickListener.$new());
      this.menuLayout.addView(minimizeBtn);

      // 布局参数
      this.menuParams = LayoutParams.$new();
      this.menuParams.type = LayoutParams.TYPE_APPLICATION_OVERLAY.value;
      this.menuParams.flags =
        LayoutParams.FLAG_NOT_FOCUSABLE.value |
        LayoutParams.FLAG_NOT_TOUCH_MODAL.value;

      this.menuParams.format = Java.use(
        "android.graphics.PixelFormat",
      ).TRANSLUCENT.value;
      this.menuParams.width = this.options.menuWidth;
      this.menuParams.height = this.options.menuHeight;
      this.menuParams.x = this.options.menuX;
      this.menuParams.y = this.options.menuY;
    } catch (error) {
      console.error("[FloatIcon] 创建菜单视图失败:", error);
    }
  };

  FloatIcon.prototype.showIcon = function () {
    if (this.isIconShown) return;
    try {
      this.windowManager.addView(this.iconView, this.iconParams);
      this.isIconShown = true;
      console.log("[FloatIcon] 图标已显示");
    } catch (error) {
      console.error("[FloatIcon] 显示图标失败:", error);
    }
  };

  FloatIcon.prototype.hideIcon = function () {
    if (!this.isIconShown) return;
    try {
      this.windowManager.removeView(this.iconView);
      this.isIconShown = false;
      console.log("[FloatIcon] 图标已隐藏");
    } catch (error) {
      console.error("[FloatIcon] 隐藏图标失败:", error);
    }
  };

  FloatIcon.prototype.showMenu = function () {
    if (this.isMenuShown) return;
    try {
      this.windowManager.addView(this.menuLayout, this.menuParams);
      this.isMenuShown = true;
      console.log("[FloatIcon] 菜单已显示");
    } catch (error) {
      console.error("[FloatIcon] 显示菜单失败:", error);
    }
  };

  FloatIcon.prototype.hideMenu = function () {
    if (!this.isMenuShown) return;
    try {
      this.windowManager.removeView(this.menuLayout);
      this.isMenuShown = false;
      console.log("[FloatIcon] 菜单已隐藏");
    } catch (error) {
      console.error("[FloatIcon] 隐藏菜单失败:", error);
    }
  };

  FloatIcon.prototype.toggleMenu = function () {
    if (this.isMenuShown) {
      this.hideMenu();
    } else {
      this.showMenu();
    }
  };

  FloatIcon.prototype.show = function () {
    Java.scheduleOnMainThread(() => {
      this.showIcon();
      //   this.showMenu();
    });
  };

  FloatIcon.prototype.destroy = function () {
    try {
      if (this.isMenuShown) this.hideMenu();
      if (this.isIconShown) this.hideIcon();
      instance = null;
      console.log("[FloatIcon] 已销毁");
    } catch (error) {
      console.error("[FloatIcon] 销毁失败:", error);
    }
  };

  return FloatIcon;
})();

// 导出
if (typeof module !== "undefined" && module.exports) {
  module.exports = FloatIcon;
}

Java.scheduleOnMainThread(() => {
  const iconBase64 =
    "iVBORw0KGgoAAAANSUhEUgAABAAAAAQACAYAAAB/HSuDAAAQAElEQVR4Aezde5ClaV0f8Kd77jO77LIXUXCzpNQYLzGKMVopkxCIohhJtIIkEWVjQioGrdJoYkxZATR4IWXYaMVKKhoowEJcQAyUgeIWEQxqRJQQlfvusi4sy7CXme7p2zk5p3t6prunL+fyPO/7XD7LnO5z3vd5n+f3+/zmn/7O7LIY/EOAAAECBAgQIECAAAECBAjULhAEANWPWIMECBAgQIAAAQIECBAgQCBMHgD8p2e97stf/O13/esXfcsrfv3ffcMvffBHn/wLj/7Lr79z+P1f++Lh877mpy9+71f/5Me+90k/+bbnffWLfvr7n/QzXweXAAECBAgQIECAAAECBAgQyERgVMauvwHwU99015N/6umveeno+pVfP/fsX/+Wn/sHr3/rcLDw/oXB8GeGITwjLIQvGi6E6xY2Vy2EhYVwdvR64iCsP2VlffVHLqw/+r+f8xU/+t7v+sp/c8fmkstf/uPfecM7fuyvvPTJlz/6RoAAAQIECBAgQIAAAQIECHQgMD5iVwAwCAvPGQyHd7zo6Xe94AUveMfxn3/26/97GAzfOLr21OFwGAaDwei1MXoNwnDz/TBs/m98bzi+Nvo0ej9eu7p+6asevXT+pc/40ue+6Zlf+syTP/60V710Y33w5MF6eM74YC8CBAgQIECAAAECBAgQIECgE4HNQ3YFAAsLC09eCKP/DRee/+cfHF5YDMf+cRj9kf/4tTH6gX8YBmH08/3oweH40ub3y2/C5veFhTB6fPwrDBdGa0avtY3Vpz32uq966PTJU3dsrG+Mn/c3AIJ/CBAgQIAAAQIECBAgQIBAVwJb5+wKALZ+ig/hxlvOhbPnTp1afXQ9PHL+wuiH9mHYGGyEjY2N0Z/+j17j76PXOBQIm6HA6If9MHqN/xbA5mu8fhBOH39MuO0xXxY+5/rHnzl94kxYu7Qa/EOAAAECBAgQIECAAAECBAh0KHD5qF0BwOmzJ8JNj7su3PL468ND918ISxeXw2c//XC4dPHS1g/+g8Ho++g1HI5/7A+jZGD02vx1ebvxt4XRvY1wcvQD/63X3RZuvu7mcMO5G8PK0kpYFQCMgbwIECBAgAABAgQIECBAgEBnAtsH7QoAPvf2Gx6+5fOuD488sBQ+++Aj4dFHL4x+xh+GpaVLYX1tPaxtrIf18Wt9PWyMvg9Gf9o/GIUB4/8ewPg1GH0ef18frofHnrsl3HL9reGmUQBwbHAsLD26PNpjI1wcPHL39uG+EyBAgAABAgQIECBAgAABAkkFrmy+KwB4+IGlc5/80Plw/pMPhUcefiSsra2FhYWFsDBatTEY/9C/EQaD0Ws4eg2GW3/0P/6hf/zX/0ev8a7D0feNsB6OHz8Wbjp3U1hYXwgXH14Kly5cGt8O96196Imbb3whQIAAAQIECBAgQIAAAQIEEgtc3X70o/3Whzuf+etfvLy8/IWfefCz4fz5h8Ly8tYP7OO7qwsXw6fXPhLW19fC2uhP/9dHr+HoB//BOAi4/DcABqPv4/+XgPXhWlg//mi496E/DY+cfzQ8ev5CWHpkabzN5uuei396+1O+5FlP2vzgCwECBAgQIECAAAECBAgQIJBOYMfOVwKAtcHKt2yM/8N+Cxubf+I/XrN4bDGcueFkuBA+Fe4fvDesDB4N478JMP6j/+HoB/7xmuHoT/zHn8MoEBi/Xzu2FIaPvT+sHDsf3nX/G8IDF+8bLwvLgwvhDy++MyyN9ljZWLpj86IvBAgQIECAAAECBAgQIECAQDKBnRtfCQBWL61+/crapXD89EI4fcOJcN0tp8OpG46H8V/nP7v2uHB8eCb82eLvhLXBxVEIMNj6VwHG/zrA6LUx+uF//FobrIa1G+7Z3P/SxcVwcePh8H8uviW8+eFXhHc8/Kvhnkt/Mro3DKvrl75u9MYvAgQIECBAgAABAgQIECBAIJ3Arp2vBgDrK1+2ujb6AX5t/Nf8x6/VsL6+Gr7mGV8S/tUvPzt8+x3fFtYXLoVPnnlP+MzpPwzLJz4Vxn8LYPxaO/5IWL7u42H51v8bwrH18Lwf+cHwsre8JPzd7/qmMP5bAcNRQDAcjt6NXiEshPWN1duDfwgQIECAAAECBAgQIECAAIGEAru3vhIArKysPH51dTWsrq2EldWVsLRyb/indz4lfNsP/M1wy+ffGJ51x7PDj7/kp8OXfeVXhHO3HgsXTt4TNsb/DYDBICyd/VhYO3U+/K1v+obwwtGap4y+P+H2zws/9PzvDf/1V342DEYBwPi1ffT6xvoN2+99J0CAAAECBAgQIECAAAECBBII7NnySgCwtr563egV1tbXwsMr7wpf++03hi/4y39x1/LxD//jEOAXX/uK8G3f/NwwHP1gPwyD8K1Pf0Z47Tt+I3zf6E/+v3wUEOx86El/9SvCs777722u3b4+GG6c2n7vOwECBAgQIECAAAECBAgQIBBfYO+OVwKA8V//H7+W1+8Lw8WPhKd+xz/ctfbuD38k/OB3fvfo9V1h/P6p/+hrw8ZgI6wcf3t42nf+7c1rO+/vfPg7/8kzRx+Ho9fo1+a/BjD67hcBAgQIECBAgAABAgQIECCQSuCafa8EAMPB4OLoFRaPfSKcOX5duOUJT9i1+M7nvzDcd/fdo9c94c4XvDB8zm03hY1jHw6nTi6Fz/n828Le+zsfvu328V4LW5cWFsLi4rGV4B8CBAgQIECAAAECBAgQIEAgkcC1214NAIaDB8Z/on/y2IVwYvFc+MyfffLa1dtXRn+Y/6l7PxNOnro/HFs8FT59333bd7a+j+5vvdn6eu/Hd98/vnj84a07vhIgQIAAAQIECBAgQIAAAQLRBfbZ8EoAMLr34cFwY/QD/blwbOFcePdr3jy6dPXXD7zw+eEJT7w9POH228P4/Rtf/rZw/PjoT/UXToa3vPquzWs77199MoRX/NKrd34MJ46dvnvXBR8IECBAgAABAgQIECBAgACBaAL7bXQlABgOFn53fWMjrF56bBgOToffes3/Ch993wevPHP7F35BeMkrXx5e8ssvDxce2give+X/DMurJ8PqxmL4jV/9tXDxkUfD9v3x2u0Hf/89fxBe9bLXbH8cfR+OAoCT7xm98YsAAQIECBAgQIAAAQIECBCIL7DvjlcCgJPrp183/hsAyyuPCRvrp0evM+El//zO8KoXvzp86p5Ph+FwGO6/+4HwX37ileGHn/0TYXWwHB5cPhWW1xfDxbUQfviO7w8//+/vDPd+/BOba+/52CfCi37sZ8Nz/v6/2HPwQjh1/OzL9lz0kQABAgQIECBAgAABAgQIEIgisP8mi9uX7/yjH3zvIAx+98LqWvjM0vHw0MrG6LUefu3lbwv/7Gn/Nnzrl3xP+J5v/KHw2le8MVzaWAorowDg/NJGOL8UwoVLC+GR5YXwsl96TXj6X/+O8Jdu+2uj78/c8yf/WyedPXn9+97+x69+79YnXwkQIECAAAECBAgQIECAAIGoAgdsdiUAGN/fCGt3Lg+XNn/wP788CA9dWg8X1lfCynD5ymttcTmcuO5iuP7m5fC4x6+FMzceC4tnjofjZ46FQRhu/un/eK+DXqdOnXvxQfdcJ0CAAAECBAgQIECAAAECBOYTOOjpxZ03XvlH/+FVYXHwxuWNC2Fp42JY3vVa2vyT/zOPuRjOXrceTp4cbj56bHEYzp5dCDfecCw8/nNPhVECsHl9+8v4Xx3Yej8M15++8U3v+pPXv2rrs68ECBAgQIAAAQIECBAgQIBAZIEDt9sVAIxXvf4D/+1bBwsbH1oZjH7gHyyHlcuv1cGlcMPNq+HU6Gf89Y0QPvXAevjY3Svh7vsuhfvuvxTW14fhxPHF8MQ/d268zZXXwsLC5vtTJ85+/D0fedM3b37whQABAgQIECBAgAABAgQIEEggcPCW1wQA46XHzyx842Bx8JHxf+hvbbAS1gdrYWOwPvohfxAuXRqEez+xEi4sbV1bWxuE5Usb4RP3L29+X1reGG+x6zX64f+em66/6am7LvpAgAABAgQIECBAgAABAgQIxBU4ZLd9A4A3ve9XPv74E2e+9OSJs+8Y/+C//XrgwbVw3ydXNsOA4XCwa9vx3wAY/02ABx5c2XX9ulM3/NYXnL35i976/td+dNcNHwgQIECAAAECBAgQIECAAIGoAodttm8AMH7grv931+q7P/g/nvKYczc/78Sxkx/c/lsAw+GeP+EfDsfLd7y2Pp8+ce5DN5/7vO/7nY+++W+M99qxwFsCBAgQIECAAAECBAgQIEAgvsChOx4YAGw/9Zt//Lpf+L2PvfWLb77xtqfeeO7WXzx78jHvO3ns1IOLC4urm2sWFsLi4uLq+Nr4/+LvxjO3/uLjRmt//+Nv+wvv/OCv/efgHwIECBAgQIAAAQIECBAgQKADgcOPODIA2H78nR+46+3v/uAbnvt7H3vLV/3BPb956/s/8dunPnDfexbGr/ff+9unxtfG99794Tc+9+2jtdvP+U6AAAECBAgQIECAAAECBAh0IHDEERMHAEfs4zYBAgQIECBAgAABAgQIECDQo8BRRwsAjhJynwABAgQIECBAgAABAgQI5C9wZIUCgCOJLCBAgAABAgQIECBAgAABArkLHF2fAOBoIysIECBAgAABAgQIECBAgEDeAhNUJwCYAMkSAgQIECBAgAABAgQIECCQs8AktQkAJlGyhgABAgQIECBAgAABAgQI5CswUWUCgImYLCJAgAABAgQIECBAgAABArkKTFaXAGAyJ6sIECBAgAABAgQIECBAgECeAhNWJQCYEMoyAgQIECBAgAABAgQIECCQo8CkNQkAJpWyjgABAgQIECBAgAABAgQI5CcwcUUCgImpLCRAgAABAgQIECBAgAABArkJTF6PAGByKysJECBAgAABAgQIECBAgEBeAlNUIwCYAstSAgQIECBAgAABAgQIECCQk8A0tQgAptGylgABAgQIECBAgAABAgQI5CMwVSUCgKm4LCZAgAABAgQIECBAgAABArkITFeHAGA6L6sJECBAgAABAgQIECBAgEAeAlNWIQCYEsxyAgQIECBAgAABAgQIECCQg8C0NQgAphWzngABAgQIECBAgAABAgQI9C8wdQUCgKnJPECAAAECBAgQIECAAAECBPoWmP58AcD0Zp4gQIAAAQIECBAgQIAAAQL9CsxwugBgBjSPECBAgAABAgQIECBAgACBPgVmOVsAMIuaZwgQIECAAAECBAgQIECAQH8CM50sAJiJzUMECBAgQIAAAQIECBAgQKAvgdnOFQDM5uYpAgQIECBAgAABAgQIECDQj8CMpwoAZoTzGAECBAgQIECAAAECBAgQ6ENg1jMFALPKeY4AAQIECBAgQIAAAQIECHQvMPOJAoCZ6TxIgAABAgQIECBAgAABAgS6Fpj9PAHA7HaeJECAAAECBAgQIECAAAEC3QrMcZoAYA48jxIgQIAAYMvSQgAAEABJREFUAQIECBAgQIAAgS4F5jlLADCPnmcJECBAgAABAgQIECBAgEB3AnOdJACYi8/DBAgQIECAAAECBAgQIECgK4H5zhEAzOfnaQIECBAgQIAAAQIECBAg0I3AnKcIAOYE9DgBAgQIECBAgAABAgQIEOhCYN4zBADzCnqeAAECBAgQIECAAAECBAikF5j7BAHA3IQ2IECAAAECBAgQIECAAAECqQXm318AML+hHQgQIECAAAECBAgQIECAQFqBCLsLACIg2oIAAQIECBAgQIAAAQIECKQUiLG3ACCGoj0IECBAgAABAgQIECBAgEA6gSg7CwCiMNqEAAECBAgQIECAAAECBAikEoizrwAgjqNdCBAgQIAAAQIECBAgQIBAGoFIuwoAIkHahgABAgQIECBAgAABAgQIpBCItacAIJakfQgQIECAAAECBAgQIECAQHyBaDsKAKJR2ogAAQIECBAgQIAAAQIECMQWiLefACCepZ0IECBAgAABAgQIECBAgEBcgYi7CQAiYtqKAAECBAgQIECAAAECBAjEFIi5lwAgpqa9CBAgQIAAAQIECBAgQIBAPIGoOwkAonLajAABAgQIECBAgAABAgQIxBKIu48AIK6n3QgQIECAAAECBAgQIECAQByByLsIACKD2o4AAQIECBAgQIAAAQIECMQQiL2HACC2qP0IECBAgAABAgQIECBAgMD8AtF3EABEJ7UhAQIECBAgQIAAAQIECBCYVyD+8wKA+KZ2JECAAAECBAgQIECAAAEC8wkkeFoAkADVlgQIECBAgAABAgQIECBAYB6BFM8KAFKo2pMAAQIECBAgQIAAAQIECMwukORJAUASVpsSIECAAAECBAgQIECAAIFZBdI8JwBI42pXAgQIECBAgAABAgQIECAwm0CipwQAiWBtS4AAAQIECBAgQIAAAQIEZhFI9YwAIJWsfQkQIECAAAECBAgQIECAwPQCyZ4QACSjtTEBAgQIECBAgAABAgQIEJhWIN16AUA6WzsTIECAAAECBAgQIECAAIHpBBKuFgAkxLU1AQIECBAgQIAAAQIECBCYRiDlWgFASl17EyBAgAABAgQIECBAgACByQWSrhQAJOW1OQECBAgQIECAAAECBAgQmFQg7ToBQFpfuxMgQIAAAQIECBAgQIAAgckEEq8SACQGtj0BAgQIECBAgAABAgQIEJhEIPUaAUBqYfsTIECAAAECBAgQIECAAIGjBZKvEAAkJ3YAAQIECBAgQIAAAQIECBA4SiD9fQFAemMnECBAgAABAgQIECBAgACBwwU6uCsA6ADZEQQIECBAgAABAgQIECBA4DCBLu4JALpQdgYBAgQIECBAgAABAgQIEDhYoJM7AoBOmB1CgAABAgQIECBAgAABAgQOEujmugCgG2enECBAgAABAgQIECBAgACB/QU6uioA6AjaMQQIECBAgAABAgQIECBAYD+Brq4JALqSdg4BAgQIECBAgAABAgQIELhWoLMrAoDOqB1EgAABAgQIECBAgAABAgT2CnT3WQDQnbWTCBAgQIAAAQIECBAgQIDAboEOPwkAOsR2FAECBAgQIECAAAECBAgQ2CnQ5XsBQJfaziJAgAABAgQIECBAgAABAlcFOn0nAOiU22EECBAgQIAAAQIECBAgQGBboNvvAoBuvZ1GgAABAgQIECBAgAABAgS2BDr+KgDoGNxxBAgQIECAAAECBAgQIEBgLND1SwDQtbjzCBAgQIAAAQIECBAgQIBACJ0bCAA6J3cgAQIECBAgQIAAAQIECBDoXkAA0L25EwkQIECAAAECBAgQIECgdYEe+hcA9IDuSAIECBAgQIAAAQIECBBoW6CP7gUAfag7kwABAgQIECBAgAABAgRaFuildwFAL+wOJUCAAAECBAgQIECAAIF2BfrpXADQj7tTCRAgQIAAAQIECBAgQKBVgZ76FgD0BO9YAgQIECBAgAABAgQIEGhToK+uBQB9yTuXAAECBAgQIECAAAECBFoU6K1nAUBv9A4mQIAAAQIECBAgQIAAgfYE+utYANCfvZMJECBAgAABAgQIECBAoDWBHvsVAPSI72gCBAgQIECAAAECBAgQaEugz24FAH3qO5sAAQIECBAgQIAAAQIEWhLotVcBQK/8DidAgAABAgQIECBAgACBdgT67VQA0K+/0wkQIECAAAECBAgQIECgFYGe+xQA9DwAxxMgQIAAAQIECBAgQIBAGwJ9dykA6HsCzidAgAABAgQIECBAgACBFgR671EA0PsIFECAAAECBAgQIECAAAEC9Qv036EAoP8ZqIAAAQIECBAgQIAAAQIEahfIoD8BQAZDUAIBAgQIECBAgAABAgQI1C2QQ3cCgBymoAYCBAgQIECAAAECBAgQqFkgi94EAFmMQREECBAgQIAAAQIECBAgUK9AHp0JAPKYgyoIECBAgAABAgQIECBAoFaBTPoSAGQyCGUQIECAAAECBAgQIECAQJ0CuXQlAMhlEuogQIAAAQIECBAgQIAAgRoFsulJAJDNKBRCgAABAgQIECBAgAABAvUJ5NORACCfWaiEAAECBAgQIECAAAECBGoTyKgfAUBGw1AKAQIECBAgQIAAAQIECNQlkFM3AoCcpqEWAgQIECBAgAABAgQIEKhJIKteBABZjUMxBAgQIECAAAECBAgQIFCPQF6dCADymodqCBAgQIAAAQIECBAgQKAWgcz6EABkNhDlECBAgAABAgQIECBAgEAdArl1IQDIbSLqIUCAAAECBAgQIECAAIEaBLLrQQCQ3UgURIAAAQIECBAgQIAAAQLlC+TXgQAgv5moiAABAgQIECBAgAABAgRKF8iwfgFAhkNREgECBAgQIECAAAECBAiULZBj9QKAHKeiJgIECBAgQIAAAQIECBAoWSDL2gUAWY5FUQQIECBAgAABAgQIECBQrkCelQsA8pyLqggQIECAAAECBAgQIECgVIFM6xYAZDoYZREgQIAAAQIECBAgQIBAmQK5Vi0AyHUy6iJAgAABAgQIECBAgACBEgWyrVkAkO1oFEaAAAECBAgQIECAAAEC5QnkW7EAIN/ZqIwAAQIECBAgQIAAAQIEShPIuF4BQMbDURoBAgQIECBAgAABAgQIlCWQc7UCgJynozYCBAgQIECAAAECBAgQKEkg61oFAFmPR3EECBAgQIAAAQIECBAgUI5A3pUKAPKej+oIECBAgAABAgQIECBAoBSBzOsUAGQ+IOURIECAAAECBAgQIECAQBkCuVcpAMh9QuojQIAAAQIECBAgQIAAgRIEsq9RAJD9iBRIgAABAgQIECBAgAABAvkL5F+hACD/GamQAAECBAgQIECAAAECBHIXKKA+AUABQ1IiAQIECBAgQIAAAQIECOQtUEJ1AoASpqRGAgQIECBAgAABAgQIEMhZoIjaBABFjEmRBAgQIECAAAECBAgQIJCvQBmVCQDKmJMqCRAgQIAAAQIECBAgQCBXgULqEgAUMihlEiBAgAABAgQIECBAgECeAqVUJQAoZVLqJECAAAECBAgQIECAAIEcBYqpSQBQzKgUSoAAAQIECBAgQIAAAQL5CZRTkQCgnFmplAABAgQIECBAgAABAgRyEyioHgFAQcNSKgECBAgQIECAAAECBAjkJVBSNQKAkqalVgIECBAgQIAAAQIECBDISaCoWgQARY1LsQQIECBAgAABAgQIECCQj0BZlQgAypqXagkQIECAAAECBAgQIEAgF4HC6hAAFDYw5RIgQIAAAQIECBAgQIBAHgKlVSEAKG1i6iVAgAABAgQIECBAgACBHASKq0EAUNzIFEyAAAECBAgQIECAAAEC/QuUV4EAoLyZqZgAAQIECBAgQIAAAQIE+hYo8HwBQIFDUzIBAgQIECBAgAABAgQI9CtQ4ukCgBKnpmYCBAgQIECAAAECBAgQ6FOgyLMFAEWOTdEECBAgQIAAAQIECBAg0J9AmScLAMqcm6oJECBAgAABAgQIECBAoC+BQs8VABQ6OGUTIECAAAECBAgQIECAQD8CpZ4qACh1cuomQIAAAQIECBAgQIAAgT4Eij1TAFDs6BROgAABAgQIECBAgAABAt0LlHuiAKDc2amcAAECBAgQIECAAAECBLoWKPg8AUDBw1M6AQIECBAgQIAAAQIECHQrUPJpAoCSp6d2AgQIECBAgAABAgQIEOhSoOizBABFj0/xBAgQIECAAAECBAgQINCdQNknCQDKnp/qCRAgQIAAAQIECBAgQKArgcLPEQAUPkDlEyBAgAABAgQIECBAgEA3AqWfIgAofYLqJ0CAAAECBAgQIECAAIEuBIo/QwBQ/Ag1QIAAAQIECBAgQIAAAQLpBco/QQBQ/gx1QIAAAQIECBAgQIAAAQKpBSrYXwBQwRC1QIAAAQIECBAgQIAAAQJpBWrYXQBQwxT1QIAAAQIECBAgQIAAAQIpBarYWwBQxRg1QYAAAQIECBAgQIAAAQLpBOrYWQBQxxx1QYAAAQIECBAgQIAAAQKpBCrZVwBQySC1QYAAAQIECBAgQIAAAQJpBGrZVQBQyyT1QYAAAQIECBAgQIAAAQIpBKrZUwBQzSg1QoAAAQIECBAgQIAAAQLxBerZUQBQzyx1QoAAAQIECBAgQIAAAQKxBSraTwBQ0TC1QoAAAQIECBAgQIAAAQJxBWraTQBQ0zT1QoAAAQIECBAgQIAAAQIxBaraSwBQ1Tg1Q4AAAQIECBAgQIAAAQLxBOraSQBQ1zx1Q4AAAQIECBAgQIAAAQKxBCrbRwBQ2UC1Q4AAAQIECBAgQIAAAQJxBGrbRQBQ20T1Q4AAAQIECBAgQIAAAQIxBKrbQwBQ3Ug1RIAAAQIECBAgQIAAAQLzC9S3gwCgvpnqiAABAgQIECBAgAABAgTmFajweQFAhUPVEgECBAgQIECAAAECBAjMJ1Dj0wKAGqeqJwIECBAgQIAAAQIECBCYR6DKZwUAVY5VUwQIECBAgAABAgQIECAwu0CdTwoA6pyrrggQIECAAAECBAgQIEBgVoFKnxMAVDpYbREgQIAAAQIECBAgQIDAbAK1PiUAqHWy+iJAgAABAgQIECBAgACBWQSqfUYAUO1oNUaAAAECBAgQIECAAAEC0wvU+4QAoN7Z6owAAQIECBAgQIAAAQIEphWoeL0AoOLhao0AAQIECBAgQIAAAQIEphOoebUAoObp6o0AAQIECBAgQIAAAQIEphGoeq0AoOrxao4AAQIECBAgQIAAAQIEJheoe6UAoO756o4AAQIECBAgQIAAAQIEJhWofJ0AoPIBa48AAQIECBAgQIAAAQIEJhOofZUAoPYJ648AAQIECBAgQIAAAQIEJhGofo0AoPoRa5AAAQIECBAgQIAAAQIEjhaof4UAoP4Z65AAAQIECBAgQIAAAQIEjhJo4L4AoIEha5EAAQIECBAgQIAAAQIEDhdo4a4AoIUp65EAAQIECBAgQFXB02AAABAASURBVIAAAQIEDhNo4p4AoIkxa5IAAQIECBAgQIAAAQIEDhZo444AoI0565IAAQIECBAgQIAAAQIEDhJo5LoAoJFBa5MAAQIECBAgQIAAAQIE9hdo5aoAoJVJ65MAAQIECBAgQIAAAQIE9hNo5poAoJlRa5QAAQIECBAgQIAAAQIErhVo54oAoJ1Z65QAAQIECBAgQIAAAQIE9go09FkA0NCwtUqAAAECBAgQIECAAAECuwVa+iQAaGnaeiVAgAABAgQIECBAgACBnQJNvRcANDVuzRIgQIAAAQIECBAgQIDAVYG23gkA2pq3bgkQIECAAAECBAgQIEBgW6Cx7wKAxgauXQIECBAgQIAAAQIECBDYEmjtqwCgtYnrlwABAgQIECBAgAABAgTGAs29BADNjVzDBAgQIECAAAECBAgQIBBCewYCgPZmrmMCBAgQIECAAAECBAgQaFBAANDg0LVMgAABAgQIECBAgACB1gVa7F8A0OLU9UyAAAECBAgQIECAAIG2BZrsXgDQ5Ng1TYAAAQIECBAgQIAAgZYF2uxdANDm3HVNgAABAgQIECBAgACBdgUa7VwA0OjgtU2AAAECBAgQIECAAIFWBVrtWwDQ6uT1TYAAAQIECBAgQIAAgTYFmu1aANDs6DVOgAABAgQIECBAgACBFgXa7VkA0O7sdU6AAAECBAgQIECAAIH2BBruWADQ8PC1ToAAAQIECBAgQIAAgdYEWu5XANDy9PVOgAABAgQIECBAgACBtgSa7lYA0PT4NU+AAAECBAgQIECAAIGWBNruVQDQ9vx1T4AAAQIECBAgQIAAgXYEGu9UAND4bwDtEyBAgAABAgQIECBAoBWB1vsUALT+O0D/BAgQIECAAAECBAgQaEOg+S4FAM3/FgBAgAABAgQIECBAgACBFgT0KADwe4AAAQIECBAgQIAAAQIE6hfQYRAA+E1AgAABAgQIECBAgAABAtULaDAIAPwmIECAAAECBAgQIECAAIHqBTQ4EvA3AEYIfhEgQIAAAQIECBAgQIBAzQJ6GwsIAMYKXgQIECBAgAABAgQIECBQr4DONgUEAJsMvhAgQIAAAQIECBAgQIBArQL62hIQAGw5+EqAAAECBAgQIECAAAECdQro6rKAAOAyhG8ECBAgQIAAAQIECBAgUKOAnrYFBADbEr4TIECAAAECBAgQIECAQH0COroiIAC4QuENAQIECBAgQIAAAQIECNQmoJ+rAgKAqxbeESBAgAABAgQIECBAgEBdArrZISAA2IHhLQECBAgQIECAAAECBAjUJKCXnQICgJ0a3hMgQIAAAQIECBAgQIBAPQI62SUgANjF4QMBAgQIECBAgAABAgQI1CKgj90CAoDdHj4RIECAAAECBAgQIECAQB0CutgjIADYA+IjAQIECBAgQIAAAQIECNQgoIe9AgKAvSI+EyBAgAABAgQIECBAgED5Ajq4RkAAcA2JCwQIECBAgAABAgQIECBQuoD6rxUQAFxr4goBAgQIECBAgAABAgQIlC2g+n0EBAD7oLhEgAABAgQIECBAgAABAiULqH0/AQHAfiquESBAgAABAgQIECBAgEC5AirfV0AAsC+LiwQIECBAgAABAgQIECBQqoC69xcQAOzv4ioBAgQIECBAgAABAgQIlCmg6gMEBAAHwLhMgAABAgQIECBAgAABAiUKqPkgAQHAQTKuEyBAgAABAgQIECBAgEB5Aio+UEAAcCCNGwQIECBAgAABAgQIECBQmoB6DxYQABxs4w4BAgQIECBAgAABAgQIlCWg2kMEBACH4LhFgAABAgQIECBAgAABAiUJqPUwAQHAYTruESBAgAABAgQIECBAgEA5Aio9VEAAcCiPmwQIECBAgAABAgQIECBQioA6DxcQABzu4y4BAgQIECBAgAABAgQIlCGgyiMEBABHALlNgAABAgQIECBAgAABAiUIqPEoAQHAUULuEyBAgAABAgQIECBAgED+Aio8UkAAcCSRBQQIECBAgAABAgQIECCQu4D6jhYQABxtZAUBAgQIECBAgAABAgQI5C2gugkEBAATIFlCgAABAgQIECBAgAABAjkLqG0SAQHAJErWECBAgAABAgQIECBAgEC+AiqbSEAAMBGTRQQIECBAgAABAgQIECCQq4C6JhMQAEzmZBUBAgQIECBAgAABAgQI5CmgqgkFBAATQllGgAABAgQIECBAgAABAjkKqGlSAQHApFLWESBAgAABAgQIECBAgEB+AiqaWEAAMDGVhQQIECBAgAABAgQIECCQm4B6JhcQAExuZSUBAgQIECBAgAABAgQI5CWgmikEBABTYFlKgAABAgQIECBAgAABAjkJqGUaAQHANFrWEiBAgAABAgQIECBAgEA+AiqZSkAAMBWXxQQIECBAgAABAgQIECCQi4A6phMQAEznZTUBAgQIECBAgAABAgQI5CGgiikFBABTgllOgAABAgQIECBAgAABAjkIqGFaAQHAtGLWEyBAgAABAgQIECBAgED/AiqYWkAAMDWZBwgQIECAAAECBAgQIECgbwHnTy8gAJjezBMECBAgQIAAAQIECBAg0K+A02cQEADMgOYRAgQIECBAgAABAgQIEOhTwNmzCAgAZlHzDAECBAgQIECAAAECBAj0J+DkmQQEADOxeYgAAQIECBAgQIAAAQIE+hJw7mwCAoDZ3DxFgAABAgQIECBAgAABAv0IOHVGAQHAjHAeI0CAAAECBAgQIECAAIE+BJw5q4AAYFY5zxEgQIAAAQIECBAgQIBA9wJOnFlAADAznQcJECBAgAABAgQIECBAoGsB580uIACY3c6TBAgQIECAAAECBAgQINCtgNPmEBAAzIHnUQIECBAgQIAAAQIECBDoUsBZ8wgIAObR8ywBAgQIECBAgAABAgQIdCfgpLkEBABz8XmYAAECBAgQIECAAAECBLoScM58AgKA+fw8TYAAAQIECBAgQIAAAQLdCDhlTgEBwJyAHidAgAABAgQIECBAgACBLgScMa+AAGBeQc8TIECAAAECBAgQIECAQHoBJ8wtIACYm9AGBAgQIECAAAECBAgQIJBawP7zCwgA5je0AwECBAgQIECAAAECBAikFbB7BAEBQAREWxAgQIAAAQIECBAgQIBASgF7xxAQAMRQtAcBAgQIECBAgAABAgQIpBOwcxQBAUAURpsQIECAAAECBAgQIECAQCoB+8YREADEcbQLAQIECBAgQIAAAQIECKQRsGskAQFAJEjbECBAgAABAgQIECBAgEAKAXvGEhAAxJK0DwECBAgQIECAAAECBAjEF7BjNAEBQDRKGxEgQIAAAQIECBAgQIBAbAH7xRMQAMSztBMBAgQIECBAgAABAgQIxBWwW0QBAUBETFsRIECAAAECBAgQIECAQEwBe8UUEADE1LQXAQIECBAgQIAAAQIECMQTsFNUAQFAVE6bESBAgAABAgQIECBAgEAsAfvEFRAAxPW0GwECBAgQIECAAAECBAjEEbBLZAEBQGRQ2xEgQIAAAQIECBAgQIBADAF7xBYQAMQWtR8BAgQIECBAgAABAgQIzC9gh+gCAoDopDYkQIAAAQIECBAgQIAAgXkFPB9fQAAQ39SOBAgQIECAAAECBAgQIDCfgKcTCAgAEqDakgABAgQIECBAgAABAgTmEfBsCgEBQApVexIgQIAAAQIECBAgQIDA7AKeTCIgAEjCalMCBAgQIECAAAECBAgQmFXAc2kEBABpXO1KgAABAgQIECBAgAABArMJeCqRgAAgEaxtCRAgQIAAAQIECBAgQGAWAc+kEhAApJK1LwECBAgQIECAAAECBAhML+CJZAICgGS0NiZAgAABAgQIECBAgACBaQWsTycgAEhna2cCBAgQIECAAAECBAgQmE7A6oQCAoCEuLYmQIAAAQIECBAgQIAAgWkErE0pIABIqWtvAgQIECBAgAABAgQIEJhcwMqkAgKApLw2J0CAAAECBAgQIECAAIFJBaxLKyAASOtrdwIECBAgQIAAAQIECBCYTMCqxAICgMTAtidAgAABAgQIECBAgACBSQSsSS0gAEgtbH8CBAgQIECAAAECBAgQOFrAiuQCAoDkxA4gQIAAAQIECBAgQIAAgaME3E8vIABIb+wEAgQIECBAgAABAgQIEDhcwN0OBAQAHSA7ggABAgQIECBAgAABAgQOE3CvCwEBQBfKziBAgAABAgQIECBAgACBgwXc6URAANAJs0MIECBAgAABAgQIECBA4CAB17sREAB04+wUAgQIECBAgAABAgQIENhfwNWOBAQAHUE7hgABAgQIECBAgAABAgT2E3CtKwEBQFfSziFAgAABAgQIECBAgACBawVc6UxAANAZtYMIECBAgAABAgQIECBAYK+Az90JCAC6s3YSAQIECBAgQIAAAQIECOwW8KlDAQFAh9iOIkCAAAECBAgQIECAAIGdAt53KSAA6FLbWQQIECBAgAABAgQIECBwVcC7TgUEAJ1yO4wAAQIECBAgQIAAAQIEtgV871ZAANCtt9MIECBAgAABAgQIECBAYEvA144FBAAdgzuOAAECBAgQIECAAAECBMYCXl0LCAC6FnceAQIECBAgQIAAAQIECITAoHMBAUDn5A4kQIAAAQIECBAgQIAAAQLdCwgAujd3IgECBAgQIECAAAECBFoX0H8PAgKAHtAdSYAAAQIECBAgQIAAgbYFdN+HgACgD3VnEiBAgAABAgQIECBAoGUBvfciIADohd2hBAgQIECAAAECBAgQaFdA5/0ICAD6cXcqAQIECBAgQIAAAQIEWhXQd08CAoCe4B1LgAABAgQIECBAgACBNgV03ZeAAKAveecSIECAAAECBAgQIECgRQE99yYgAOiN3sEECBAgQIAAAQIECBBoT0DH/QkIAPqzdzIBAgQIECBAgAABAgRaE9BvjwICgB7xHU2AAAECBAgQIECAAIG2BHTbp4AAoE99ZxMgQIAAAQIECBAgQKAlAb32KiAA6JXf4QQIECBAgAABAgQIEGhHQKf9CggA+vV3OgECBAgQIECAAAECBFoR0GfPAgKAngfgeAIECBAgQIAAAQIECLQhoMu+BQQAfU/A+QQIECBAgAABAgQIEGhBQI+9CwgAeh+BAggQIECAAAECBAgQIFC/gA77FxAA9D8DFRAgQIAAAQIECBAgQKB2Af1lICAAyGAISiBAgAABAgQIECBAgEDdArrLQUAAkMMU1ECAAAECBAgQIECAAIGaBfSWhYAAIIsxKIIAAQIECBAgQIAAAQL1CugsDwEBQB5zUAUBAgQIECBAgAABAgRqFdBXJgICgEwGoQwCBAgQIECAAAECBAjUKaCrXAQEALlMQh0ECBAgQIAAAQIECBCoUUBP2QgIALIZhUIIECBAgAABAgQIECBQn4CO8hEQAOQzC5UQIECAAAECBAgQIECgNgH9ZCQgAMhoGEohQIAAAQI31iR2AAAQAElEQVQECBAgQIBAXQK6yUlAAJDTNNRCgAABAgQIECBAgACBmgT0kpWAACCrcSiGAAECBAgQIECAAAEC9QjoJC8BAUBe81ANAQIECBAgQIAAAQIEahHQR2YCAoDMBqIcAgQIECBAgAABAgQI1CGgi9wEBAC5TUQ9BAgQIECAAAECBAgQqEFAD9kJCACyG4mCCBAgQIAAAQIECBAgUL6ADvITEADkNxMVESBAgAABAgQIECBAoHQB9WcoIADIcChKIkCAAAECBAgQIECAQNkCqs9RQACQ41TURIAAAQIECBAgQIAAgZIF1J6lgAAgy7EoigABAgQIECBAgAABAuUKqDxPAQFAnnNRFQECBAgQIECAAAECBEoVUHemAgKATAejLAIECBAgQIAAAQIECJQpoOpcBQQAuU5GXQQIECBAgAABAgQIEChRQM3ZCggAsh2NwggQIECAAAECBAgQIFCegIrzFRAA5DsblREgQIAAAQIECBAgQKA0AfVmLCAAyHg4SiNAgAABAgQIECBAgEBZAqrNWUAAkPN01EaAAAECBAgQIECAAIGSBNSatYAAIOvxKI4AAQIECBAgQIAAAQLlCKg0bwEBQN7zUR0BAgQIECBAgAABAgRKEVBn5gICgMwHpDwCBAgQIECAAAECBAiUIaDK3AUEALlPSH0ECBAgQIAAAQIECBAoQUCN2QsIALIfkQIJECBAgAABAgQIECCQv4AK8xcQAOQ/IxUSIECAAAECBAgQIEAgdwH1FSAgAChgSEokQIAAAQIECBAgQIBA3gKqK0FAAFDClNRIgAABAgQIECBAgACBnAXUVoSAAKCIMSmSAAECBAgQIECAAAEC+QqorAwBAUAZc1IlAQIECBAgQIAAAQIEchVQVyECAoBCBqVMAgQIECBAgAABAgQI5CmgqlIEBAClTEqdBAgQIECAAAECBAgQyFFATcUICACKGZVCCRAgQIAAAQIECBAgkJ+AisoREACUMyuVEiBAgAABAgQIECBAIDcB9RQkIAAoaFhKJUCAAAECBAgQIECAQF4CqilJQABQ0rTUSoAAAQIECBAgQIAAgZwE1FKUgACgqHEplgABAgQIECBAgAABAvkIqKQsAQFAWfNSLQECBAgQIECAAAECBHIRUEdhAgKAwgamXAIECBAgQIAAAQIECOQhoIrSBAQApU1MvQQIECBAgAABAgQIEMhBQA3FCQgAihuZggkQIECAAAECBAgQINC/gArKExAAlDczFRMgQIAAAQIECBAgQKBvAecXKCAAKHBoSiZAgAABAgQIECBAgEC/Ak4vUUAAUOLU1EyAAAECBAgQIECAAIE+BZxdpIAAoMixKZoAAQIECBAgQIAAAQL9CTi5TAEBQJlzUzUBAgQIECBAgAABAgT6EnBuoQICgEIHp2wCBAgQIECAAAECBAj0I+DUUgUEAKVOTt0ECBAgQIAAAQIECBDoQ8CZxQoIAIodncIJECBAgAABAgQIECDQvYATyxUQAJQ7O5UTIECAAAECBAgQIECgawHnFSwgACh4eEonQIAAAQIECBAgQIBAtwJOK1lAAFDy9NROgAABAgQIECBAgACBLgWcVbSAAKDo8SmeAAECBAgQIECAAAEC3Qk4qWwBAUDZ81M9AQIECBAgQIAAAQIEuhJwTuECAoDCB6h8AgQIECBAgAABAgQIdCPglNIFBAClT1D9BAgQIECAAAECBAgQ6ELAGcULCACKH6EGCBAgQIAAAQIECBAgkF7ACeULCADKn6EOCBAgQIAAAQIECBAgkFrA/hUICAAqGKIWCBAgQIAAAQIECBAgkFbA7jUICABqmKIeCBAgQIAAAQIECBAgkFLA3lUICACqGKMmCBAgQIAAAQIECBAgkE7AznUICADqmKMuCBAgQIAAAQIECBAgkErAvpUICAAqGaQ2CBAgQIAAAQIECBAgkEbArrUICABqmaQ+CBAgQIAAAQIECBAgkELAntUICACqGaVGCBAgQIAAAQIECBAgEF/AjvUICADqmaVOCBAgQIAAAQIECBAgEFvAfhUJCAAqGqZWCBAgQIAAAQIECBAgEFfAbjUJCABqmqZeCBAgQIAAAQIECBAgEFPAXlUJCACqGqdmCBAgQIAAAQIECBAgEE/ATnUJCADqmqduCBAgQIAAAQIECBAgEEvAPpUJCAAqG6h2CBAgQIAAAQIECBAgEEfALrUJCABqm6h+CBAgQIAAAQIECBAgEEPAHtUJCACqG6mGCBAgQIAAAQIECBAgML+AHeoTEADUN1MdESBAgAABAgQIECBAYF4Bz1coIACocKhaIkCAAAECBAgQIECAwHwCnq5RQABQ41T1RIAAAQIECBAgQIAAgXkEPFulgACgyrFqigABAgQIECBAgAABArMLeLJOAQFAnXPVFQECBAgQIECAAAECBGYV8FylAgKASgerLQIECBAgQIAAAQIECMwm4KlaBQQAtU5WXwQIECBAgAABAgQIEJhFwDPVCggAqh2txggQIECAAAECBAgQIDC9gCfqFRAA1DtbnREgQIAAAQIECBAgQGBaAesrFhAAVDxcrREgQIAAAQIECBAgQGA6AatrFhAA1DxdvREgQIAAAQIECBAgQGAaAWurFhAAVD1ezREgQIAAAQIECBAgQGByASvrFhAA1D1f3REgQIAAAQIECBAgQGBSAesqFxAAVD5g7REgQIAAAQIECBAgQGAyAatqFxAA1D5h/REgQIAAAQIECBAgQGASAWuqFxAAVD9iDRIgQIAAAQIECBAgQOBoASvqFxAA1D9jHRIgQIAAAQIECBAgQOAoAfcbEBAANDBkLRIgQIAAAQIECBAgQOBwAXdbEBAAtDBlPRIgQIAAAQIECBAgQOAwAfeaEBAANDFmTRIgQIAAAQIECBAgQOBgAXfaEBAAtDFnXRIgQIAAAQIECBAgQOAgAdcbERAANDJobRIgQIAAAQIECBAgQGB/AVdbERAAtDJpfRIgQIAAAQIECBAgQGA/AdeaERAANDNqjRIgQIAAAQIECBAgQOBaAVfaERAAtDNrnRIgQIAAAQIECBAgQGCvgM8NCQgAGhq2VgkQIECAAAECBAgQILBbwKeWBAQALU1brwQIECBAgAABAgQIENgp4H1TAgKApsatWQIECBAgQIAAAQIECFwV8K4tAQFAW/PWLQECBAgQIECAAAECBLYFfG9MQADQ2MC1S4AAAQIECBAgQIAAgS0BX1sTEAC0NnH9EiBAgAABAgQIECBAYCzg1ZyAAKC5kWuYAAECBAgQIECAAAECITBoT0AA0N7MdUyAAAECBAgQIECAAAECDQoIABocupYJECBAgAABAgQIEGhdQP8tCggAWpy6ngkQIECAAAECBAgQaFtA900KCACaHLumCRAgQIAAAQIECBBoWUDvbQoIANqcu64JECBAgAABAgQIEGhXQOeNCggAGh28tgkQIECAAAECBAgQaFVA360KCABanby+CRAgQIAAAQIECBBoU0DXzQoIAJodvcYJECBAgAABAgQIEGhRQM/tCggA2p29zgkQIECAAAECBAgQaE9Axw0LCAAaHr7WCRAgQIAAAQIECBBoTUC/LQsIAFqevt4JECBAgAABAgQIEGhLQLdNCwgAmh6/5gkQIECAAAECBAgQaElAr20LCADanr/uCRAgQIAAAQIECBBoR0CnjQsIABr/DaB9AgQIECBAgAABAgRaEdBn6wICgNZ/B+ifAAECBAgQIECAAIE2BHTZvIAAoPnfAgAIECBAgAABAgQIEGhBQI8EBAB+DxAgQIAAAQIECBAgQKB+AR0SCAIAvwkIECBAgAABAgQIECBQvYAGCQQBgN8EBAgQIECAAAECBAgQqF5AgwRGAv4GwAjBLwIECBAgQIAAAQIECNQsoDcCYwEBwFjBiwABAgQIECBAgAABAvUK6IzApoAAYJPBFwIECBAgQIAAAQIECNQqoC8CWwICgC0HXwkQIECAAAECBAgQIFCngK4IXBYQAFyG8I0AAQIECBAgQIAAAQI1CuiJwLaAAGBbwncCBAgQIECAAAECBAjUJ6AjAlcEBABXKLwhQIAAAQIECBAgQIBAbQL6IXBVQABw1cI7AgQIECBAgAABAgQI1CWgGwI7BAQAOzC8JUCAAAECBAgQIECAQE0CeiGwU0AAsFPDewIECBAgQIAAAQIECNQjoBMCuwQEALs4fCBAgAABAgQIECBAgEAtAvogsFtAALDbwycCBAgQIECAAAECBAjUIaALAnsEBAB7QHwkQIAAAQIECBAgQIBADQJ6ILBXQACwV8RnAgQIECBAgAABAgQIlC+gAwLXCAgAriFxgQABAgQIECBAgAABAqULqJ/AtQICgGtNXCFAgAABAgQIECBAgEDZAqonsI+AAGAfFJcIECBAgAABAgQIECBQsoDaCewnIADYT8U1AgQIECBAgAABAgQIlCugcgL7CggA9mVxkQABAgQIECBAgAABAqUKqJvA/gICgP1dXCVAgAABAgQIECBAgECZAqomcICAAOAAGJcJECBAgAABAgQIECBQooCaCRwkIAA4SMZ1AgQIECBAgAABAgQIlCegYgIHCggADqRxgwABAgQIECBAgAABAqUJqJfAwQICgINt3CFAgAABAgQIECBAgEBZAqolcIiAAOAQHLcIECBAgAABAgQIECBQkoBaCRwmIAA4TMc9AgQIECBAgAABAgQIlCOgUgKHCggADuVxkwABAgQIECBAgAABAqUIqJPA4QICgMN93CVAgAABAgQIECBAgEAZAqokcISAAOAIILcJECBAgAABAgQIECBQgoAaCRwlIAA4Ssh9AgQIECBAgAABAgQI5C+gQgJHCggAjiSygAABAgQIECBAgAABArkLqI/A0QICgKONrCBAgAABAgQIECBAgEDeAqojMIGAAGACJEsIECBAgAABAgQIECCQs4DaCEwiIACYRMkaAgQIECBAgAABAgQI5CugMgITCQgAJmKyiAABAgQIECBAgAABArkKqIvAZAICgMmcrCJAgAABAgQIECBAgECeAqoiMKGAAGBCKMsIECBAgAABAgQIECCQo4CaCEwqIACYVMo6AgQIECBAgAABAgQI5CegIgITCwgAJqaykAABAgQIECBAgAABArkJqIfA5AICgMmtrCRAgAABAgQIECBAgEBeAqohMIWAAGAKLEsJECBAgAABAgQIECCQk4BaCEwjIACYRstaAgQIECBAgAABAgQI5COgEgJTCQgApuKymAABAgQIECBAgAABArkIqIPAdAICgOm8rCZAgAABAgQIECBAgEAeAqogMKWAAGBKMMsJECBAgAABAgQIECCQg4AaCEwrIACYVsx6AgQIECBAgAABAgQI9C+gAgJTCwgApibzAAECBAgQIECAAAECBPoWcD6B6QUEANObeYIAAQIECBAgQIAAAQL9CjidwAwCAoAZ0DxCgAABAgQIDBb0EAAAEABJREFUECBAgACBPgWcTWAWAQHALGqeIUCAAAECBAgQIECAQH8CTiYwk4AAYCY2DxEgQIAAAQIECBAgQKAvAecSmE1AADCbm6cIECBAgAABAgQIECDQj4BTCcwoIACYEc5jBAgQIECAAAECBAgQ6EPAmQRmFRAAzCrnOQIECBAgQIAAAQIECHQv4EQCMwsIAGam8yABAgQIECBAgAABAgS6FnAegdkFBACz23mSAAECBAgQIECAAAEC3Qo4jcAcAgKAOfA8SoAAAQIECBAgQIAAgS4FnEVgHgEBwDx6niVAgAABAgQIECBAgEB3Ak4iMJeAAGAuPg8TIECAAAECBAgQIECgKwHnEJhPQAAwn5+nCRAgQIAAAQIECBAg0I2AUwjMKSAAmBPQ4wQIECBAgAABAgQIEOhCwBkE5hUQAMwr6HkCBAgQIECAAAECBAikF3ACgbkFBABzE9qAAAECBAgQIECAAAECqQXsT2B+AQHA/IZ2IECAAAECBAgQIECAQFoBuxOIICAAiIBoCwIECBAgQIAAAQIECKQUsDeBGAICgBiK9iBAgAABAgQIECBAgEA6ATsTiCIgAIjCaBMCBAgQIECAAAECBAikErAvgTgCAoA4jnYhQIAAAQIECBAgQIBAGgG7EogkIACIBGkbAgQIECBAgAABAgQIpBCwJ4FYAgKAWJL2IUCAAAECBAgQIECAQHwBOxKIJiAAiEZpIwIECBAgQIAAAQIECMQWsB+BeAICgHiWdiJAgAABAgQIECBAgEBcAbsRiCggAIiIaSsCBAgQIECAAAECBAjEFLAXgZgCAoCYmvYiQIAAAQIECBAgQIBAPAE7EYgqIACIymkzAgQIECBAgAABAgQIxBKwD4G4AgKAuJ52I0CAAAECBAgQIECAQBwBuxCILCAAiAxqOwIECBAgQIAAAQIECMQQsAeB2AICgNii9iNAgAABAgQIECBAgMD8AnYgEF1AABCd1IYECBAgQIAAAQIECBCYV8DzBOILCADim9qRAAECBAgQIECAAAEC8wl4mkACAQFAAlRbEiBAgAABAgQIECBAYB4BzxJIISAASKFqTwIECBAgQIAAAQIECMwu4EkCSQQEAElYbUqAAAECBAgQIECAAIFZBTxHII2AACCNq10JECBAgAABAgQIECAwm4CnCCQSEAAkgrUtAQIECBAgQIAAAQIEZhHwDIFUAgKAVLL2JUCAAAECBAgQIECAwPQCniCQTEAAkIzWxgQIECBAgAABAgQIEJhWwHoC6QQEAOls7UyAAAECBAgQIECAAIHpBKwmkFBAAJAQ19YECBAgQIAAAQIECBCYRsBaAikFBAApde1NgAABAgQIECBAgACByQWsJJBUQACQlNfmBAgQIECAAAECBAgQmFTAOgJpBQQAaX3tToAAAQIECBAgQIAAgckErCKQWEAAkBjY9gQIECBAgAABAgQIEJhEwBoCqQUEAKmF7U+AAAECBAgQIECAAIGjBawgkFxAAJCc2AEECBAgQIAAAQIECBA4SsB9AukFBADpjZ1AgAABAgQIECBAgACBwwXcJdCBgACgA2RHECBAgAABAgQIECBA4DAB9wh0ISAA6ELZGQQIECBAgAABAgQIEDhYwB0CnQgIADphdggBAgQIECBAgAABAgQOEnCdQDcCAoBunJ1CgAABAgQIECBAgACB/QVcJdCRgACgI2jHECBAgAABAgQIECBAYD8B1wh0JSAA6EraOQQIECBAgAABAgQIELhWwBUCnQkIADqjdhABAgQIECBAgAABAgT2CvhMoDsBAUB31k4iQIAAAQIECBAgQIDAbgGfCHQoIADoENtRBAgQIECAAAECBAgQ2CngPYEuBQQAXWo7iwABAgQIECBAgAABAlcFvCPQqYAAoFNuhxEgQIAAAQIECBAgQGBbwHcC3QoIALr1dhoBAgQIECBAgAABAgS2BHwl0LGAAKBjcMcRIECAAAECBAgQIEBgLOBFoGsBAUDX4s4jQIAAAQIECBAgQIBACAwIdC4gAOic3IEECBAgQIAAAQIECBAgQKB7AQFA9+ZOJECAAAECBAgQIECgdQH9E+hBQADQA7ojCRAgQIAAAQIECBBoW0D3BPoQEAD0oe5MAgQIECBAgAABAgRaFtA7gV4EBAC9sDuUAAECBAgQIECAAIF2BXROoB8BAUA/7k4lQIAAAQIECBAgQKBVAX0T6ElAANATvGMJECBAgAABAgQIEGhTQNcE+hIQAPQl71wCBAgQIECAAAECBFoU0DOB3gQEAL3RO5gAAQIECBAgQIAAgfYEdEygPwEBQH/2TiZAgAABAgQIECBAoDUB/RLoUUAA0CO+owkQIECAAAECBAgQaEtAtwT6FBAA9KnvbAIECBAgQIAAAQIEWhLQK4FeBQQAvfI7nAABAgQIECBAgACBdgR0SqBfAQFAv/5OJ0CAAAECBAgQIECgFQF9EuhZQADQ8wAcT4AAAQIECBAgQIBAGwK6JNC3gACg7wk4nwABAgQIECBAgACBFgT0SKB3AQFA7yNQAAECBAgQIECAAAEC9QvokED/AgKA/megAgIECBAgQIAAAQIEahfQH4EMBAQAGQxBCQQIECBAgAABAgQI1C2gOwI5CAgAcpiCGggQIECAAAECBAgQqFlAbwSyEBAAZDEGRRAgQIAAAQIECBAgUK+AzgjkISAAyGMOqiBAgAABAgQIECBAoFYBfRHIREAAkMkglEGAAAECBAgQIECAQJ0CuiKQi4AAIJdJqIMAAQIECBAgQIAAgRoF9EQgGwEBQDajUAgBAgQIECBAgAABAvUJ6IhAPgICgHxmoRICBAgQIECAAAECBGoT0A+BjAQEABkNQykECBAgQIAAAQIECNQloBsCOQkIAHKahloIECBAgAABAgQIEKhJQC8EshIQAGQ1DsUQIECAAAECBAgQIFCPgE4I5CUgAMhrHqohQIAAAQIECBAgQKAWAX0QyExAAJDZQJRDgAABAgQIECBAgEAdArogkJuAACC3iaiHAAECBAgQIECAAIEaBPRAIDsBAUB2I1EQAQIECBAgQIAAAQLlC+iAQH4CAoD8ZqIiAgQIECBAgAABAgRKF1A/gQwFBAAZDkVJBAgQIECAAAECBAiULaB6AjkKCABynIqaCBAgQIAAAQIECBAoWUDtBLIUEABkORZFESBAgAABAgQIECBQroDKCeQpIADIcy6qIkCAAAECBAgQIECgVAF1E8hUQACQ6WCURYAAAQIECBAgQIBAmQKqJpCrgAAg18moiwABAgQIECBAgACBEgXUTCBbAQFAtqNRGAECBAgQIECAAAEC5QmomEC+AgKAfGejMgIECBAgQIAAAQIEShNQL4GMBQQAGQ9HaQQIECBAgAABAgQIlCWgWgI5CwgAcp6O2ggQIECAAAECBAgQKElArQSyFhAAZD0exREgQIAAAQIECBAgUI6ASgnkLSAAyHs+qiNAgAABAgQIECBAoBQBdRLIXEAAkPmAlEeAAAECBAgQIECAQBkCqiSQu4AAIPcJqY8AAQIECBAgQIAAgRIE1EggewEBQPYjUiABAgQIECBAgAABAvkLqJBA/gICgPxnpEICBAgQIECAAAECBHIXUB+BAgQEAAUMSYkECBAgQIAAAQIECOQtoDoCJQgIAEqYkhoJECBAgAABAgQIEMhZQG0EihAQABQxJkUSIECAAAECBAgQIJCvgMoIlCEgAChjTqokQIAAAQIECBAgQCBXAXURKERAAFDIoJRJgAABAgQIECBAgECeAqoiUIqAAKCUSamTAAECBAgQIECAAIEcBdREoBgBAUAxo1IoAQIECBAgQIAAAQL5CaiIQDkCAoByZqVSAgQIECBAgAABAgRyE1APgYIEBAAFDUupBAgQIECAAAECBAjkJaAaAiUJCABKmpZaCRAgQIAAAQIECBDISUAtBIoSEAAUNS7FEiBAgAABAgQIECCQj4BKCJQlIAAoa16qJUCAAAECBAgQIEAgFwF1EChMQABQ2MCUS4AAAQIECBAgQIBAHgKqIFCagACgtImplwABAgQIECBAgACBHATUQKA4AQFAcSNTMAECBAgQIECAAAEC/QuogEB5AgKA8mamYgIECBAgQIAAAQIE+hZwPoECBQQABQ5NyQQIECBAgAABAgQI9CvgdAIlCggASpyamgkQIECAAAECBAgQ6FPA2QSKFBAAFDk2RRMgQIAAAQIECBAg0J+AkwmUKSAAKHNuqiZAgAABAgQIECBAoC8B5xIoVEAAUOjglE2AAAECBAgQIECAQD8CTiVQqoAAoNTJqZsAAQIECBAgQIAAgT4EnEmgWAEBQLGjUzgBAgQIECBAgAABAt0LOJFAuQICgHJnp3ICBAgQIECAAAECBLoWcB6BggUEAAUPT+kECBAgQIAAAQIECHQr4DQCJQsIAEqentoJECBAgAABAgQIEOhSwFkEihYQABQ9PsUTIECAAAECBAgQINCdgJMIlC0gACh7fqonQIAAAQIECBAgQKArAecQKFxAAFD4AJVPgAABAgQIECBAgEA3Ak4hULqAAKD0CaqfAAECBAgQIECAAIEuBJxBoHgBAUDxI9QAAQIECBAgQIAAAQLpBZxAoHwBAUD5M9QBAQIECBAgQIAAAQKpBexPoAIBAUAFQ9QCAQIECBAgQIAAAQJpBexOoAYBAUANU9QDAQIECBAgQIAAAQIpBexNoAoBAUAVY9QEAQIECBAgQIAAAQLpBOxMoA4BAUAdc9QFAQIECBAgQIAAAQKpBOxLoBIBAUAlg9QGAQIECBAgQIAAAQJpBOxKoBYBAUAtk9QHAQIECBAgQIAAAQIpBOxJoBoBAUA1o9QIAQIECBAgQIAAAQLxBexIoB4BAUA9s9QJAQIECBAgQIAAAQKxBexHoCIBAUBFw9QKAQIECBAgQIAAAQJxBexGoCYBAUBN09QLAQIECBAgQIAAAQIxBexFoCoBAUBV49QMAQIECBAgQIAAAQLxBOxEoC4BAUBd89QNAQIECBAgQIAAAQKxBOxDoDIBAUBlA9UOAQIECBAgQIAAAQJxBOxCoDYBAUBtE9UPAQIECBAgQIAAAQIxBOxBoDoBAUB1I9UQAQIECBAgQIAAAQLzC9iBQH0CAoD6ZqojAgQIECBAgAABAgTmFfA8gQoFBAAVDlVLBAgQIECAAAECBAjMJ+BpAjUKCABqnKqeCBAgQIAAAQIECBCYR8CzBKoUEABUOVZNESBAgAABAgQIECAwu4AnCdQpIACoc666IkCAAAECBAgQIEBgVgHPEahUQABQ6WC1RYAAAQIECBAgQIDAbAKeIlCrgACg1snqiwABAgQIECBAgACBWQQ8Q6BaAQFAtaPVGAECBAgQIECAAAEC0wt4gkC9AgKAemerMwIECBAgQIAAAQIEphWwnkDFAgKAioerNQIECBAgQIAAAQIEphOwmkDNAgKAmqerNwIECCZ9hcAAABAASURBVBAgQIAAAQIEphGwlkDVAgKAqserOQIECBAgQIAAAQIEJhewkkDdAgKAuuerOwIECBAgQIAAAQIEJhWwjkDlAgKAygesPQIECBAgQIAAAQIEJhOwikDtAgKA2iesPwIECBAgQIAAAQIEJhGwhkD1AgKA6kesQQIECBAgQIAAAQIEjhawgkD9AgKA+mesQwIECBAgQIAAAQIEjhJwn0ADAgKABoasRQIECBAgQIAAAQIEDhdwl0ALAgKAFqasRwIECBAgQIAAAQIEDhNwj0ATAgKAJsasSQIECBAgQIAAAQIEDhZwh0AbAgKANuasSwIECBAgQIAAAQIEDhJwnUAjAgKARgatTQIECBAgQIAAAQIE9hdwlUArAgKAViatTwIECBAgQIAAAQIE9hNwjUAzAgKAZkatUQIECBAgQIAAAQIErhVwhUA7AgKAdmatUwIECBAgQIAAAQIE9gr4TKAhAQFAQ8PWKgECBAgQIECAAAECuwV8ItCSgACgpWnrlQABAgQIECBAgACBnQLeE2hKQADQ1Lg1S4AAAQIECBAgQIDAVQHvCLQlIABoa966JUCAAAECBAgQIEBgW8B3Ao0JCAAaG7h2CRAgQIAAAQIECBDYEvCVQGsCAoDWJq5fAgQIECBAgAABAgTGAl4EmhMQADQ3cg0TIECAAAECBAgQIBACAwLtCQgA2pu5jgkQIECAAAECBAgQIECgQQEBQIND1zIBAgQIECBAgACB1gX0T6BFAQFAi1PXMwECBAgQIECAAIG2BXRPoEkBAUCTY9c0AQIECBAgQIAAgZYF9E6gTQEBQJtz1zUBAgQIECBAgACBdgV0TqBRAQFAo4PXNgECBAgQIECAAIFWBfRNoFUBAUCrk9c3AQIECBAgQIAAgTYFdE2gWQEBQLOj1zgBAgQIECBAgACBFgX0TKBdAQFAu7PXOQECBAgQIECAAIH2BHRMoGEBAUDDw9c6AQIECBAgQIAAgdYE9EugZQEBQMvT1zsBAgQIECBAgACBtgR0S6BpAQFA0+PXPAECBAgQIECAAIGWBPRKoG0BAUDb89c9AQIECBAgQIAAgXYEdEqgcQEBQOO/AbRPgAABAgQIECBAoBUBfRJoXUAA0PrvAP0TIECAAAECBAgQaENAlwSaFxAANP9bAAABAgQIECBAgACBFgT0SICAAMDvAQIECBAgQIAAAQIE6hfQIQECQQDgNwEBAgQIECBAgAABAtULaJAAgSAA8JuAAAECBAgQIECAAIHqBTRIgMBIwN8AGCH4RYAAAQIECBAgQIBAzQJ6I0BgLCAAGCt4ESBAgAABAgQIECBQr4DOCBDYFBAAbDL4QoAAAQIECBAgQIBArQL6IkBgS0AAsOXgKwECBAgQIECAAAECdQroigCBywICgMsQvhEgQIAAAQIECBAgUKOAnggQ2BYQAGxL+E6AAAECBAgQIECAQH0COiJA4IqAAOAKhTcECBAgQIAAAQIECNQmoB8CBK4KCACuWnhHgAABAgQIECBAgEBdArohQGCHgABgB4a3BAgQIECAAAECBAjUJKAXAgR2CggAdmp4T4AAAQIECBAgQIBAPQI6IUBgl4AAYBeHDwQIECBAgAABAgQI1CKgDwIEdgsIAHZ7+ESAAAECBAgQIECAQB0CuiBAYI+AAGAPiI8ECBAgQIAAAQIECNQgoAcCBPYKCAD2ivhMgAABAgQIECBAgED5AjogQOAaAQHANSQuECBAgAABAgQIECBQuoD6CRC4VkAAcK2JKwQIECBAgAABAgQIlC2gegIE9hEQAOyD4hIBAgQIECBAgAABAiULqJ0Agf0EBAD7qbhGgAABAgQIECBAgEC5AionQGBfAQHAviwuEiBAgAABAgQIECBQqoC6CRDYX0AAsL+LqwQIECBAgAABAgQIlCmgagIEDhAQABwA4zIBAgQIECBAgAABAiUKqJkAgYMEBAAHybhOgAABAgQIECBAgEB5AiomQOBAAQHAgTRuECBAgAABAgQIECBQmoB6CRA4WEAAcLCNOwQIECBAgAABAgQIlCWgWgIEDhEQAByC4xYBAgQIECBAgAABAiUJqJUAgcMEBACH6bhHgAABAgQIECBAgEA5AiolQOBQAQHAoTxuEiBAgAABAgQIECBQioA6CRA4XEAAcLiPuwQIECBAgAABAgQIlCGgSgIEjhAQABwB5DYBAgQIECBAgAABAiUIqJEAgaMEBABHCblPgAABAgQIECBAgED+AiokQOBIAQHAkUQWECBAgAABAgQIECCQu4D6CBA4WkAAcLSRFQQIECBAgAABAgQI5C2gOgIEJhAQAEyAZAkBAgQIECBAgAABAjkLqI0AgUkEBACTKFlDgAABAgQIECBAgEC+AiojQGAiAQHAREwWESBAgAABAgQIECCQq4C6CBCYTEAAMJmTVQQIECBAgAABAgQI5CmgKgIEJhQQAEwIZRkBAgQIECBAgAABAjkKqIkAgUkFBACTSllHgAABAgQIECBAgEB+AioiQGBiAQHAxFQWEiBAgAABAgQIECCQm4B6CBCYXEAAMLmVlQQIECBAgAABAgQI5CWgGgIEphAQAEyBZSkBAgQIECBAgAABAjkJqIUAgWkEBADTaFlLgAABAgQIECBAgEA+AiohQGAqAQHAVFwWEyBAgAABAgQIECCQi4A6CBCYTkAAMJ2X1QQIECBAgAABAgQI5CGgCgIEphQQAEwJZjkBAgQIECBAgAABAjkIqIEAgWkFBADTillPgAABAgQIECBAgED/AiogQGBqAQHA1GQeIECAAAECBAgQIECgbwHnEyAwvYAAYHozTxAgQIAAAQIECBAg0K+A0wkQmEFAADADmkcIECBAgAABAgQIEOhTwNkECMwiIACYRc0zBAgQIECAAAECBAj0J+BkAgRmEhAAzMTmIQIECBAgQIAAAQIE+hJwLgECswkIAGZz8xQBAgQIECBAgAABAv0IOJUAgRkFBAAzwnmMAAECBAgQIECAAIE+BJxJgMCsAgKAWeU8R4AAAQIECBAgQIBA9wJOJEBgZgEBwMx0HiRAgAABAgQIECBAoGsB5xEgMLuAAGB2O08SIECAAAECBAgQINCtgNMIEJhDQAAwB55HCRAgQIAAAQIECBDoUsBZBAjMIyAAmEfPswQIECBAgAABAgQIdCfgJAIE5hIQAMzF52ECBAgQIECAAAECBLoScA4BAvMJCADm8/M0AQIECBAgQIAAAQLdCDiFAIE5BQQAcwJ6nAABAgQIECBAgACBLgScQYDAvAICgHkFPU+AAAECBAgQIECAQHoBJxAgMLeAAGBuQhsQIECAAAECBAgQIJBawP4ECMwvIACY39AOBAgQIECAAAECBAikFbA7AQIRBAQAERBtQYAAAQIECBAgQIBASgF7EyAQQ0AAEEPRHgQIECBAgAABAgQIpBOwMwECUQQEAFEYbUKAAAECBAgQIECAQCoB+xIgEEdAABDH0S4ECBAgQIAAAQIECKQRsCsBApEEBACRIG1DgAABAgQIECBAgEAKAXsSIBBLQAAQS9I+BAgQIECAAAECBAjEF7AjAQLRBAQA0ShtRIAAAQIECBAgQIBAbAH7ESAQT0AAEM/STgQIECBAgAABAgQIxBWwGwECEQUEABExbUWAAAECBAgQIECAQEwBexEgEFNAABBT014ECBAgQIAAAQIECMQTsBMBAlEFBABROW1GgAABAgQIECBAgEAsAfsQIBBXQAAQ19NuBAgQIECAAAECBAjEEbALAQKRBQQAkUFtR4AAAQIECBAgQIBADAF7ECAQW0AAEFvUfgQIECBAgAABAgQIzC9gBwIEogsIAKKT2pAAAQIECBAgQIAAgXkFPE+AQHwBAUB8UzsSIECAAAECBAgQIDCfgKcJEEggIABIgGpLAgQIECBAgAABAgTmEfAsAQIpBAQAKVTtSYAAAQIECBAgQIDA7AKeJEAgiYAAIAmrTQkQIECAAAECBAgQmFXAcwQIpBEQAKRxtSsBAgQIECBAgAABArMJeIoAgUQCAoBEsLYlQIAAAQIECBAgQGAWAc8QIJBKQACQSta+BAgQIECAAAECBAhML+AJAgSSCQgAktHamAABAgQIECBAgACBaQWsJ0AgnYAAIJ2tnQkQIECAAAECBAgQmE7AagIEEgoIABLi2poAAQIECBAgQIAAgWkErCVAIKWAACClrr0JECBAgAABAgQIEJhcwEoCBJIKCACS8tqcAAECBAgQIECAAIFJBawjQCCtgAAgra/dCRAgQIAAAQIECBCYTMAqAgQSCwgAEgPbngABAgQIECBAgACBSQSsIUAgtYAAILWw/QkQIECAAAECBAgQOFrACgIEkgsIAJITO4AAAQIECBAgQIAAgaME3CdAIL2AACC9sRMIECBAgAABAgQIEDhcwF0CBDoQEAB0gOwIAgQIECBAgAABAgQOE3CPAIEuBAQAXSg7gwABAgQIECBAgACBgwXcIUCgEwEBQCfMDiFAgAABAgQIECBA4CAB1wkQ6EZAANCNs1MIECBAgAABAgQIENhfwFUCBDoSEAB0BO0YAgQIECBAgAABAgT2E3CNAIGuBAQAXUk7hwABAgQIECBAgACBawVcIUCgMwEBQGfUDiJAgAABAgQIECBAYK+AzwQIdCcgAOjO2kkECBAgQIAAAQIECOwW8IkAgQ4FBAAdYjuKAAECBAgQIECAAIGdAt4TINClgACgS21nESBAgAABAgQIECBwVcA7AgQ6FRAAdMrtMAIECBAgQIAAAQIEtgV8J0CgWwEBQLfeTiNAgAABAgQIECBAYEvAVwIEOhYQAHQM7jgCBAgQIECAAAECBMYCXgQIdC0gAOha3HkECBAgQIAAAQIECITAgACBzgUEAJ2TO5AAAQIECBAgQIAAAQIECHQvIADo3tyJBAgQIECAAAECBFoX0D8BAj0ICAB6QHckAQIECBAgQIAAgbYFdE+AQB8CAoA+1J1JgAABAgQIECBAoGUBvRMg0IuAAKAXdocSIECAAAECBAgQaFdA5wQI9CMgAOjH3akECBAgQIAAAQIEWhXQNwECPQkIAHqCdywBAgQIECBAgACBNgV0TYBAXwICgL7knUuAAAECBAgQIECgRQE9EyDQm4AAoDd6BxMgQIAAAQIECBBoT0DHBAj0JyAA6M/eyQQIECBAgAABAgRaE9AvAQI9CggAesR3NAECBAgQIECAAIG2BHRLgECfAgKAPvWdTYAAAQIECBAgQKAlAb0SINCrgACgV36HEyBAgAABAgQIEGhHQKcECPQrIADo19/pBAgQIECAAAECBFoR0CcBAj0LCAB6HoDjCRAgQIAAAQIECLQhoEsCBPoWEAD0PQHnEyBAgAABAgQIEGhBQI8ECPQuIADofQQKIECAAAECBAgQIFC/gA4JEOhfQADQ/wxUQIAAAQIECBAgQKB2Af0RIJCBgAAggyEogQCYyBqGAAALJElEQVQBAgQIECBAgEDdArojQCAHAQFADlNQAwECBAgQIECAAIGaBfRGgEAWAgKALMagCAIECBAgQIAAAQL1CuiMAIE8BAQAecxBFQQIECBAgAABAgRqFdAXAQKZCAgAMhmEMggQIECAAAECBAjUKaArAgRyERAA5DIJdRAgQIAAAQIECBCoUUBPBAhkIyAAyGYUCiFAgAABAgQIECBQn4COCBDIR0AAkM8sVEKAAAECBAgQIECgNgH9ECCQkYAAIKNhKIUAAQIECBAgQIBAXQK6IUAgJwEBQE7TUAsBAgQIECBAgACBmgT0QoBAVgICgKzGoRgCBAgQIECAAAEC9QjohACBvAQEAHnNQzUECBAgQIAAAQIEahHQBwECmQkIADIbiHIIECBAgAABAgQI1CGgCwIEchMQAOQ2EfUQIECAAAECBAgQqEFADwQIZCcgAMhuJAoiQIAAAQIECBAgUL6ADggQyE9AAJDfTFREgAABAgQIECBAoHQB9RMgkKGAACDDoSiJAAECBAgQIECAQNkCqidAIEcBAUCOU1ETAQIECBAgQIAAgZIF1E6AQJYCAoAsx6IoAgQIECBAgAABAuUKqJwAgTwFBAB5zkVVBAgQIECAAAECBEoVUDcBApkKCAAyHYyyCBAgQIAAAQIECJQpoGoCBHIVEADkOhl1ESBAgAABAgQIEChRQM0ECGQrIADIdjQKI0CAAAECBAgQIFCegIoJEMhXQACQ72xURoAAAQIECBAgQKA0AfUSIJCxgAAg4+EojQABAgQIECBAgEBZAqolQCBnAQFAztNRGwECBAgQIECAAIGSBNRKgEDWAgKArMejOAIECBAgQIAAAQLlCKiUAIG8BQQAec9HdQQIECBAgAABAgRKEVAnAQKZCwgAMh+Q8ggQIECAAAECBAiUIaBKAgRyFxAA5D4h9REgQIAAAQIECBAoQUCNBAhkLyAAyH5ECiRAgAABAgQIECCQv4AKCRDIX0AAkP+MVEiAAAECBAgQIEAgdwH1ESBQgIAAoIAhKZEAAQIECBAgQIBA3gKqI0CgBAEBQAlTUiMBAgQIECBAgACBnAXURoBAEQICgCLGpEgCBAgQIECAAAEC+QqojACBMgQEAGXMSZUECBAgQIAAAQIEchVQFwEChQgIAAoZlDIJECBAgAABAgQI5CmgKgIEShEQAJQyKXUSIECAAAECBAgQyFFATQQIFCMgAChmVAolQIAAAQIECBAgkJ+AiggQKEdAAFDOrFRKgAABAgQIECBAIDcB9RAgUJCAAKCgYSmVAAECBAgQIECAQF4CqiFAoCQBAUBJ01IrAQIECBAgQIAAgZwE1EKAQFECAoCixqVYAgQIECBAgAABAvkIqIQAgbIEBABlzUu1BAgQIECAAAECBHIRUAcBAoUJCAAKG5hyCRAgQIAAAQIECOQhoAoCBEoTEACUNjH1EiBAgAABAgQIEMhBQA0ECBQnIAAobmQKJkCAAAECBAgQINC/gAoIEChPQABQ3sxUTIAAAQIECBAgQKBvAecTIFCggACgwKEpmQABAgQIECBAgEC/Ak4nQKBEAQFAiVNTMwECBAgQIECAAIE+BZxNgECRAgKAIsemaAIECBAgQIAAAQL9CTiZAIEyBQQAZc5N1QQIECBAgAABAgT6EnAuAQKFCggACh2csgkQIECAAAECBAj0I+BUAgRKFRAAlDo5dRMgQIAAAQIECBDoQ8CZBAgUKyAAKHZ0CidAgAABAgQIECDQvYATCRAoV0AAUO7sVE6AAAECBAgQIECgawHnESBQsIAAoODhKZ0AAQIECBAgQIBAtwJOI0CgZAEBQMnTUzsBAgQIECBAgACBLgWcRYBA0QICgKLHp3gCBAgQIECAAAEC3Qk4iQCBsgUEAGXPT/UECBAgQIAAAQIEuhJwDgEChQsIAAofoPIJECBAgAABAgQIdCPgFAIEShcQAJQ+QfUTIECAAAECBAgQ6ELAGQQIFC8gACh+hBogQIAAAQIECBAgkF7ACQQIlC8gACh/hjogQIAAAQIECBAgkFrA/gQIVCAgAKhgiFogQIAAAQIECBAgkFbA7gQI1CAgAKhhinogQIAAAQIECBAgkFLA3gQIVCEgAKhijJogQIAAAQIECBAgkE7AzgQI1CEgAKhjjrogQIAAAQIECBAgkErAvgQIVCIgAKhkkNogQIAAAQIECBAgkEbArgQI1CIgAKhlkvogQIAAAQIECBAgkELAngQIVCMgAKhmlBohQIAAAQIECBAgEF/AjgQI1CMgAKhnljohQIAAAQIECBAgEFvAfgQIVCQgAKhomFohQIAAAQIECBAgEFfAbgQI1CQgAKhpmnohQIAAAQIECBAgEFPAXgQIVCUgAKhqnJohQIAAAQIECBAgEE/ATgQI1CUgAKhrnrohQIAAAQIECBAgEEvAPgQIVCYgAKhsoNohQIAAAQIECBAgEEfALgQI1CYgAKhtovohQIAAAQIECBAgEEPAHgQIVCcgAKhupBoiQIAAAQIECBAgML+AHQgQqE9AAFDfTHVEgAABAgQIECBAYF4BzxMgUKGAAKDCoWqJAAECBAgQIECAwHwCniZAoEYBAUCNU9UTAQIECBAgQIAAgXkEPEuAQJUCAoAqx6opAgQIECBAgAABArMLeJIAgToFBAB1zlVXBAgQIECAAAECBGYV8BwBApUKCAAqHay2CBAgQIAAAQIECMwm4CkCBGoVEADUOll9ESBAgAABAgQIEJhFwDMECFQrIACodrQaI0CAAAECBAgQIDC9gCcIEKhXQABQ72x1RoAAAQIECBAgQGBaAesJEKhYQABQ8XC1RoAAAQIECBAgQGA6AasJEKhZQABQ83T1RoAAAQIECBAgQGAaAWsJEKhaQABQ9Xg1R4AAAQIECBAgQGByASsJEKhbQABQ93x1R4AAAQIECBAgQGBSAesIEKhcQABQ+YC1R4AAAQIECBAgQGAyAasIEKhdQABQ+4T1R4AAAQIECBAgQGASAWsIEKheQABQ/Yg1SIAAAQIECBAgQOBoASsIEKhfQABQ/4x1SIAAAQIECBAgQOAoAfcJEGhAQADQwJC1SIAAAQIECBAgQOBwAXcJEGhBQADQwpT1SIAAAQIECBAgQOAwAfcIEGhCQADQxJg1SYAAAQIECBAgQOBgAXcIEGhDQADQxpx1SYAAAQIECBAgQOAgAdcJEGhEQADQyKC1SYAAAQIECBAgQGB/AVcJEGhFQADQyqT1SYAAAQIECBAgQGA/AdcIEGhGQADQzKg1SoAAAQIECBAgQOBaAVcIEGhHQADQzqx1SoAAAQIECBAgQGCvgM8ECDQkIABoaNhaJUCAAAECBAgQILBbwCcCBFoSEAC0NG29EiBAgAABAgQIENgp4D0BAk0JCACaGrdmCRAgQIAAAQIECFwV8I4AgbYEBABtzVu3BAgQIECAAAECBLYFfCdAoDEBAUBjA9cuAQIECBAgQIAAgS0BXwkQaE1AANDaxPVLgAABAgQIECBAYCzgRYBAcwICgOZGrmECBAgQIECAAAECITAgQKA9AQFAezPXMQECBAgQIECAAAECBAg0KCAAaHDoWiZAgAABAgQIEGhdQP8ECLQoIABocep6JkCAAAECBAgQaFtA9wQINCkgAGhy7JomQIAAAQIECBBoWUDvBAi0KSAAaHPuuiZAgAABAgQIEGhXQOcECDQqIABodPDaJkCAAAECBAgQaFVA3wQItCogAGh18vomQIAAAQIECBBoU0DXBAg0KyAAaHb0GidAgAABAgQIEGhRQM8ECLQr8P8BAAD//0bwbP8AAAAGSURBVAMAecC4PUWOepkAAAAASUVORK5CYII=";

  const floatIcon = new FloatIcon(iconBase64, {
    iconX: 50,
    iconY: 100,
    menuX: 200,
    menuY: 200,
    menuWidth: 80,
    menuHeight: 25,
  });

  setTimeout(() => {
    floatIcon.show();
  }, 1000);

  console.log("[FloatIcon] 悬浮图标已创建");
});
